language: php
php:
  - 7.1
  - 7.2
before_script:
  - composer global require "squizlabs/php_codesniffer=*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
script:
  - composer install
  - php -l github-status-stats.php
  - phpcs --standard=PSR1 github-status-stats.php
