language: php
php:
  - 7.1
  - 7.2
before_install:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
before_script:
  - composer global require "squizlabs/php_codesniffer=*"
script:
  - composer install
  - php -l github-status-stats.php
  - phpcs --standard=PSR1 github-status-stats.php
